# sample-workflow-windows-latest
# docs are in the repo

name: .NET Analyzers on-push-verification windows-latest
on: push

jobs:
  sample:
    name: .NET Analyzers runner

    # .NET Analyzers runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: windows-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v2

    # Ensure a compatible version of dotnet is installed.
    # The [Microsoft Code Analysis CLI](https://aka.ms/mscadocs) is built with dotnet v3.1.201.
    # A version greater than or equal to v3.1.201 of dotnet must be installed on the agent in order to run this action.
    # Remote agents already have a compatible version of dotnet installed and this step may be skipped.
    # For local agents, ensure dotnet version 3.1.201 or later is installed by including this action:
    # - uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: '3.1.x'

      # Run .NET Analyzers
    - name: Run .NET Analyzers
      uses: ./
      id: dotnet-analyzers
      with:
        projects: sample\ClassLibrary1.sln
